### PR TITLE
feat(http.cr): default to HTTPS

### PR DESCRIPTION
**Pull request by stakach**
Probably shouldn't be doing anything over HTTP anyway, so I would not consider this a breaking change.
With HTTP I was getting this error and it seems onerous to have to specify a `@custom_endpoint` for HTTPS

`Requests specifying Server Side Encryption with AWS KMS managed keys must be made over a secure connection`

### CODE REVIEW

**Comment by stakach** [comment]
@taylorfinnell fixed up the spec and a couple of other issues i ran into when using this in production.
Would you consider reviewing this pull request?

**Comment by taylorfinnell** [comment]
Hey, thanks! Happy to merge this, looks like some tests are still failing and I think it needs a `crystal tool format`

**Comment by stakach** [comment]
Sweet, that was probably it.
`crystal spec` and `ameba` are clean on my machine

**Comment by stakach** [comment]
Ahh now it's a crystal 0.34 error.
I can quickly patch that

**Comment by stakach** [comment]
@taylorfinnell I literally cannot replicate the issue with `crystal tool format` and `./spec/awscr-s3/bucket_spec.cr` that we're seeing on travis... all other specs pass

**Comment by taylorfinnell** [comment]
Yea, I can't repro it locally either, very weird. I will go ahead and merge this. Thank you!

**Pull request merged**
