### PR TITLE
Make GetObjectObject#body always be IO

### PR DESCRIPTION
**Pull request by carlhoerberg**
Currently code using this has to check which type it is.

### CODE REVIEW

**Comment by taylorfinnell** [comment]
I have not looked at it much, but this throws errors when you run the `object_put_get.cr` example in `examples/`

**Comment by carlhoerberg** [comment]
Ok, yes, this patch isn't backward compatible. `puts resp.body` will raise as there's no `IO#to_s`. One way to still be backward compatible is to add a `GetObjectOutput#body_io` instead.

**Comment by carlhoerberg** [comment]
Otherwise, to fix the example you just change the last line to `puts resp.body.gets_to_end`, or the very more efficient `IO.copy resp.body, STDOUT`

**Comment by carlhoerberg** [comment]
Created a new class for streamed objects, which only got the body_io, normal synchronus get_object now only got `body`  and it's always a string.

**Comment by taylorfinnell** [comment]
Thank you!

**Pull request merged**
