### PR TITLE
Encode object name instead of the whole URL

### LINKED ISSUE #34: Spaces in S3 object keys
Hey there! Love the shard, so thank you _very_ much. It's fantastic.

Question for you - have you run into issues uploading where the target S3 object key has spaces in it? When I attempt to do that I get the following error: 

```
HttpVersionNotSupported: The HTTP version specified is not supported. (Awscr::S3::Http::ServerError)
```

Which is a little odd in itself. When I change the key's spaces to underscores, however - all is well. Thanks so much!

### PR DESCRIPTION
**Pull request by jrester**
Fixes #34 and #60 and is based on my pull request to awscr-signer.

### CODE REVIEW

**Comment by jrester** [comment]
Any updates on this?

**Comment by taylorfinnell** [comment]
Sorry, happy to merge once the conflicts are fixed up

**Comment by jrester** [comment]
Oh, I am sorry. As far as I am concerned the CI did not fail because of my additions but rather some issues in the `timecop` library.
I will rebase my changes and update this PR.

**Comment by jrester** [comment]
Would you mind bumping the version of the `awscr-signer`? This PR depends on the new version in which my PR is included.

**Comment by taylorfinnell** [comment]
Just bumped signer

**Pull request merged**
