### PR TITLE
Allow key_count to be empty

### PR DESCRIPTION
**Pull request by omarroth**
For `ListObjectsV2`, the `key_count` can sometimes be empty or non-existent. This is a quick fix to add a default value if it's not a valid integer.

### CODE REVIEW

**Comment by taylorfinnell** [comment]
This works even if KeyCount is absent from the response?

**Comment by omarroth** [comment]
Yep!

**Comment by omarroth** [comment]
I think you mean to merge `patch-2` into `master`.

**Comment by taylorfinnell** [comment]
Oops, no idea how that happened

**Comment by samueleaton** [comment]
@taylorfinnell  Can we get a release out for this? :)

**Comment by taylorfinnell** [comment]
Done!

**Pull request merged**
