### PR TITLE
Add head_object method

### PR DESCRIPTION
**Pull request by acoustep**
Hi,

Thanks for creating this great package.

I'm in a situation where I'd like to be able to access object meta data without fetching the files.

I thought it would be useful to add this as a method `head_object` as this is the API that AWS uses. I've also added a new response type for it.

I think it would also be nice to use Crystal's `Time` class for last_modified, but I had some trouble parsing the date format so I've left it as-is.

### CODE REVIEW

**Comment by taylorfinnell** [comment]
Thank you!

I think you should be able to parse the last modified like this. https://github.com/taylorfinnell/awscr-s3/blob/master/src/awscr-s3/responses/list_objects_v2.cr#L26

Also, looks like `ameba` is not working with Crystal 0.29.0 and making CI fail. I can try to update that later today or you can if you want

**Comment by acoustep** [comment]
Ah thanks @taylorfinnell I had not seen that :).

I've updated the code to parse the time.

I'm not sure on the Ameba stuff, I'm currently using 0.28.0 on my project and haven't upgraded yet I'm afraid.

**Comment by acoustep** [comment]
I've just been looking a bit more into the timezone formatting. I'm using a aws s3 compatible api (min.io) and Last-Modified returns a format like this `Wed, 19 Jun 2019 11:55:33 GMT`.

I'm assuming AWS S3 uses the same format, and with the format `"%FT%T"` I'm unable to parse it correctly.

I was, however, able to get it working with this

```
    DATE_FORMAT = "%a, %d %b %Y %l:%M:%S"
    # ...
      last_modified_words = response.headers["Last-Modified"].split(" ")
      timezone = Time::Location.local = Time::Location.load(last_modified_words.pop)
      last_modified = last_modified_words.join(" ")
      Time.parse(last_modified, DATE_FORMAT, timezone
```

I just wanted to check this is correct for all S3 compatible APIs before I updated the pull request. Are you able to confirm if the current code works?

**Comment by taylorfinnell** [comment]
I think you are correct

https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectHEAD.html
vs
https://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html

I assumed they would be the same, my bad

**Comment by acoustep** [comment]
No worries, I've updated the code to work with the different format.

**Comment by taylorfinnell** [comment]
If you can run a `crystal tool format` should be good to merge

**Comment by acoustep** [comment]
No problem, I’m away from my machine for the next few days but I’ll get it done later this week.

**Comment by acoustep** [comment]
I've run the formatter 👍

**Comment by taylorfinnell** [comment]
Thanks!

**Pull request merged**
